// <auto-generated/>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "IME", Scope = "member", Target = "Mmu.Mlh.NetFrameworkExtensions.Areas.KeyboardHooking.Models.KeyboardInputKey.#IMEConvert", Justification = "Domain term of a Keyboard")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Pa", Scope = "member", Target = "Mmu.Mlh.NetFrameworkExtensions.Areas.KeyboardHooking.Models.KeyboardInputKey.#Pa1", Justification = "Domain term of a Keyboard")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "Domain Terma of a Keyboard", Scope = "member", Target = "~P:Mmu.Mlh.NetFrameworkExtensions.Areas.Hooking.KeyboardHooking.Domain.Models.KeyboardInputKey.Decimal")]